// src/components/TaskCard.tsx
import { useMemo } from 'react'
import { useDraggable } from '@dnd-kit/core'
import { Check, Repeat, NotePencil } from '@phosphor-icons/react'
import { useStore } from '../store/useStore'
import type { Task, ViewDensity } from '../types'
import { getDueStatus, DUE_STATUS_CONFIG } from '../types'

interface TaskCardProps {
  task: Task
}

/** 密度配置：宽 / 字号 / 内边距 / 最小高度 / 显示项 */
const densityStyles: Record<ViewDensity, {
  width: string; fontSize: string; padding: string; minH: string
  showDate: boolean; showTags: boolean; showLevel: boolean; showNote: boolean; showTagNames: boolean
}> = {
  compact: {
    width: 'w-[4.5rem]', fontSize: 'text-[11px]', padding: 'px-2 py-2', minH: 'min-h-[44px]',
    showDate: false, showTags: false, showLevel: false, showNote: false, showTagNames: false,
  },
  standard: {
    width: 'w-[7rem]', fontSize: 'text-xs', padding: 'px-2.5 py-2.5', minH: 'min-h-[68px]',
    showDate: true, showTags: true, showLevel: false, showNote: false, showTagNames: false,
  },
  detailed: {
    width: 'w-[9rem]', fontSize: 'text-[13px]', padding: 'px-3 py-3', minH: 'min-h-[90px]',
    showDate: true, showTags: true, showLevel: true, showNote: true, showTagNames: true,
  },
}

export function TaskCard({ task }: TaskCardProps) {
  const viewDensity = useStore((s) => s.viewDensity)
  const setEditingTaskId = useStore((s) => s.setEditingTaskId)
  const completeTask = useStore((s) => s.completeTask)
  const isSelectMode = useStore((s) => s.isSelectMode)
  const focusToday = useStore((s) => s.focusToday)
  const selectedTaskIds = useStore((s) => s.selectedTaskIds)
  const toggleSelectTask = useStore((s) => s.toggleSelectTask)
  const tags = useStore((s) => s.tags)
  const isSelected = selectedTaskIds.includes(task.id)
  const tagMap = useMemo(() => {
    const m: Record<string, string> = {}
    tags.forEach((t) => { m[t.id] = t.color })
    return m
  }, [tags])

  const ds = densityStyles[viewDensity]
  const dueStatus = getDueStatus(task.dueDate)
  const dueConfig = DUE_STATUS_CONFIG[dueStatus]
  const isUrgent = dueStatus === 'overdue' || dueStatus === 'today' || dueStatus === 'thisWeek'
  const isFaded = focusToday && !isUrgent
  const dueDateStr = task.dueDate
    ? new Date(task.dueDate).toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' })
    : null

  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({
    id: task.id,
    data: { task },
  })

  const style: React.CSSProperties = {
    position: 'absolute',
    left: `${task.posX * 100}%`,
    bottom: `${task.posY * 100}%`,
    // dnd-kit transform 跟随拖拽；无 CSS transition 避免点击时移位
    transform: transform
      ? `translate(-50%, 50%) translate(${transform.x}px, ${transform.y}px)`
      : 'translate(-50%, 50%)',
    zIndex: isDragging ? 50 : 10,
    touchAction: 'none',
  }

  return (
    <div
      ref={setNodeRef}
      data-task-card={task.id}
      className={`
        ${ds.width} ${ds.padding} ${ds.minH} rounded-2xl cursor-grab active:cursor-grabbing
        border border-white/70 select-none group flex flex-col justify-between
        hover:shadow-md transition-shadow duration-200
        ${isDragging ? 'shadow-lg scale-105' : 'shadow-sm'}
        ${dueStatus === 'overdue' && !isDragging ? 'ring-1 ring-red-200/60' : ''}
        ${isSelected ? 'ring-2 ring-purple-400' : ''}
        ${isFaded ? '!opacity-35' : ''}
      `}
      style={{
        ...style,
        opacity: isFaded ? 0.35 : undefined,
        background: isSelected ? 'var(--card-selected-bg)' : 'var(--card-bg)',
        backdropFilter: 'blur(8px)',
        borderLeft: dueConfig.color ? `3px solid ${dueConfig.color}` : '3px solid transparent',
      }}
      {...listeners}
      {...attributes}
      onClick={(e) => {
        e.stopPropagation()
        if (isDragging) return
        if (isSelectMode || e.ctrlKey || e.metaKey) {
          toggleSelectTask(task.id)
          return
        }
        setEditingTaskId(task.id)
      }}
      onContextMenu={(e) => {
        e.preventDefault()
        toggleSelectTask(task.id)
      }}
    >
      {/* 选中标记 + 完成按钮 */}
      {!isDragging && (
        <>
          {(isSelectMode || isSelected) && (
            <div
              className={`absolute -top-2 -left-2 w-5 h-5 rounded-full border-2 flex items-center justify-center shadow-sm transition-all z-10 ${
                isSelected
                  ? 'bg-purple-400 border-purple-400 text-white'
                  : 'bg-white border-gray-300 opacity-0 group-hover:opacity-100'
              }`}
            >
              {isSelected && <Check weight="bold" className="w-2.5 h-2.5" />}
            </div>
          )}
          {!isSelectMode && (
            <button
              className="absolute -top-2 -right-2 w-5 h-5 rounded-full bg-white border border-gray-200
                         flex items-center justify-center opacity-0 group-hover:opacity-100 transition-all
                         hover:bg-green-50 hover:border-green-300 hover:scale-110 shadow-sm z-10"
              onClick={(e) => { e.stopPropagation(); completeTask(task.id) }}
              title="完成"
            >
              <Check weight="bold" className="w-2.5 h-2.5 text-green-500" />
            </button>
          )}
        </>
      )}

      {/* 上部：级别 + 标题 */}
      <div className="min-w-0">
        {ds.showLevel && (
          <div className="flex items-center gap-1 mb-1.5">
            <span className="w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: `hsl(${task.importanceLevel * 30}, 60%, 70%)` }} />
            <span className="text-[9px] text-gray-400">I{task.importanceLevel}</span>
            <span className="w-1.5 h-1.5 rounded-full ml-0.5 flex-shrink-0" style={{ background: `hsl(${220 - task.urgencyLevel * 30}, 60%, 70%)` }} />
            <span className="text-[9px] text-gray-400">U{task.urgencyLevel}</span>
          </div>
        )}
        <div className={`${ds.fontSize} font-semibold leading-snug flex items-center gap-1`} style={{ color: 'var(--text-primary)' }}>
          <span className="truncate">{task.title || '未命名'}</span>
          {task.recurrence && (
            <Repeat weight="bold" className="w-3 h-3 flex-shrink-0 text-purple-400" />
          )}
        </div>
      </div>

      {/* 下部：日期 + 标签 + 备注 */}
      <div className="min-w-0 mt-1">
        {/* 截止日期 — 始终占位保证高度 */}
        {ds.showDate && (
          <div className="text-[11px] leading-tight h-[16px]">
            {dueDateStr && (
              <span className="font-medium inline-flex items-center gap-1" style={{ color: dueConfig.color || undefined }}>
                {dueStatus !== 'normal' && dueStatus !== 'none' && (
                  <span className="text-[9px] px-1 py-px rounded align-[1px]" style={{ backgroundColor: dueConfig.bg, color: dueConfig.color }}>
                    {dueConfig.label}
                  </span>
                )}
                {dueDateStr}
              </span>
            )}
          </div>
        )}

        {/* 标签 — 标准：色点 / 详细：色点+名称 */}
        {ds.showTags && task.tags.length > 0 && (
          <div className={`flex flex-wrap items-center ${ds.showTagNames ? 'gap-1.5' : 'gap-1'} ${ds.showDate ? 'mt-0.5' : ''}`}>
            {task.tags.slice(0, ds.showTagNames ? 4 : 3).map((tagId) => {
              const tag = tags.find((t) => t.id === tagId)
              return ds.showTagNames && tag ? (
                <span key={tagId} className="flex items-center gap-1 text-[9px] text-gray-500">
                  <span className="w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ backgroundColor: tag.color }} />
                  <span className="truncate max-w-[3rem]">{tag.name}</span>
                </span>
              ) : (
                <span key={tagId} className="w-2 h-2 rounded-full flex-shrink-0" style={{ backgroundColor: tagMap[tagId] || '#ccc' }} />
              )
            })}
            {task.tags.length > (ds.showTagNames ? 4 : 3) && (
              <span className="text-[9px] text-gray-400">+{task.tags.length - (ds.showTagNames ? 4 : 3)}</span>
            )}
          </div>
        )}

        {/* 备注摘要（仅详细模式） */}
        {ds.showNote && task.note && (
          <div className="flex items-start gap-1 mt-1.5">
            <NotePencil weight="fill" className="w-2.5 h-2.5 text-gray-350 flex-shrink-0 mt-[1px]" />
            <div className="text-[10px] leading-snug line-clamp-2" style={{ color: 'var(--text-secondary)' }}>
              {task.note.slice(0, 80)}
            </div>
          </div>
        )}
      </div>

      {/* 拖拽时等级角标 */}
      {isDragging && (
        <div className="absolute -bottom-6 left-1/2 -translate-x-1/2 bg-white rounded-full px-2 py-0.5 text-[11px] text-gray-500 shadow-md whitespace-nowrap font-medium">
          I{task.importanceLevel} · U{task.urgencyLevel}
        </div>
      )}
    </div>
  )
}

// web/src/components/task/TaskCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useTaskStore, getDueStatus, DUE_STATUS_CONFIG } from '@/stores/task'
import type { TaskOut } from '@/api/tasks'

const props = defineProps<{
  task: TaskOut
  density?: 'compact' | 'standard' | 'detailed'
  dimmed?: boolean
}>()

const emit = defineEmits<{
  click: [task: TaskOut]
  complete: [task: TaskOut]
  delete: [task: TaskOut]
  contextmenu: [task: TaskOut]
}>()

const store = useTaskStore()
const isCompact = computed(() => props.density === 'compact')
const isDetailed = computed(() => props.density === 'detailed')

const dueStatus = computed(() => getDueStatus(props.task.dueDate))
const dueConfig = computed(() => DUE_STATUS_CONFIG[dueStatus.value])

const dueDateStr = computed(() => {
  if (!props.task.dueDate) return null
  const d = new Date(props.task.dueDate)
  return `${d.getMonth() + 1}月${d.getDate()}日`
})

const tags = computed(() => {
  const t = props.task.tags
  if (!t || !t.length) return []
  if (typeof t[0] === 'string') {
    return (t as string[]).map(uuid => store.tags.find(tg => tg.uuid === uuid)).filter(Boolean) as { uuid: string; name: string; color: string }[]
  }
  return t as { uuid: string; name: string; color: string }[]
})

const checklistProgress = computed(() => {
  const total = Number(props.task.checklistTotal)
  if (!total) return null
  const done = Number(props.task.checklistCompleted)
  return `☑ ${done}/${total}`
})
</script>

<template>
  <div
    class="task-card"
    :class="[
      `density-${density ?? 'standard'}`,
      {
        completed: task.completed,
        'due-overdue': dueStatus === 'overdue',
        'due-today': dueStatus === 'today',
        'is-dimmed': dimmed,
      },
    ]"
    :style="{
      borderLeftColor: dueConfig.color || 'transparent',
    }"
    @click="emit('click', task)"
    @contextmenu.prevent="emit('contextmenu', task)"
    role="button"
    tabindex="0"
    @keydown.enter="emit('click', task)"
  >
    <!-- 完成 / 选中指示 -->
    <template v-if="!task.completed">
      <button
        class="complete-btn"
        :title="task.completed ? '取消完成' : '标记完成'"
        @click.stop="emit('complete', task)"
      >
        <svg viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M3 8l3 3 7-7" />
        </svg>
      </button>
    </template>

    <!-- 标题行 -->
    <div class="card-title-row">
      <span class="card-title">{{ task.title || '未命名' }}</span>
      <svg
        v-if="task.recurrence"
        class="recurrence-icon"
        viewBox="0 0 16 16"
        width="12"
        height="12"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
      >
        <path d="M1 4v4h4M15 12v-4h-4" />
        <path d="M12.5 2.5a7 7 0 00-10 2M3.5 13.5a7 7 0 0010-2" />
      </svg>
    </div>

    <!-- 底部行：标签 + 日期 -->
    <div class="card-footer">
      <!-- 标签 —— 紧凑模式隐藏，标准模式显示色点，详细模式显示名称 -->
      <div v-if="!isCompact && tags.length" class="card-tags">
        <template v-if="!isDetailed">
          <span
            v-for="tag in tags.slice(0, 3)"
            :key="tag.uuid"
            class="tag-dot"
            :style="{ backgroundColor: tag.color }"
          />
          <span v-if="tags.length > 3" class="tag-extra">+{{ tags.length - 3 }}</span>
        </template>
        <template v-else>
          <span
            v-for="tag in tags"
            :key="tag.uuid"
            class="tag-chip"
            :style="{ color: tag.color }"
          >
            <span class="tag-chip-dot" :style="{ backgroundColor: tag.color }" />
            {{ tag.name }}
          </span>
        </template>
      </div>

      <!-- 截止日期 + 检查项 -->
      <div v-if="dueDateStr || checklistProgress" class="card-due">
        <span v-if="checklistProgress" class="checklist-text">{{ checklistProgress }}</span>
        <span
          v-if="dueDateStr"
          class="due-text"
        >
          <span
            v-if="dueConfig.label"
            class="due-status-chip"
            :style="{ backgroundColor: dueConfig.bg, color: dueConfig.color }"
          >{{ dueConfig.label }}</span>
          {{ dueDateStr }}
        </span>
      </div>
    </div>

    <!-- 备注预览（仅详细模式） -->
    <div v-if="isDetailed && task.note" class="card-note">
      {{ task.note }}
    </div>

    <!-- 删除按钮（绝对定位，悬停时显示） -->
    <button
      class="delete-btn"
      title="删除"
      @click.stop="emit('delete', task)"
    >&times;</button>
  </div>
</template>

<style scoped>
/* ── 基础卡片 ── */
.task-card {
  position: relative;
  background: rgba(255, 255, 255, 0.85);
  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);
  border: 1px solid rgba(255, 255, 255, 0.7);
  border-left: 3px solid transparent;
  border-radius: 16px;
  padding: 10px 12px;
  cursor: grab;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.06);
  transition: box-shadow 0.2s ease, border-color 0.2s ease, opacity 0.2s ease;
  user-select: none;
  display: flex;
  flex-direction: column;
  gap: 4px;
  min-height: 68px;
  max-width: var(--task-card-max-width);
}

.task-card:hover {
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

:root.dark .task-card {
  background: rgba(40, 40, 47, 0.85);
  border-color: rgba(255, 255, 255, 0.08);
}

.task-card:active {
  cursor: grabbing;
}

/* ── 状态 ── */
.task-card.completed {
  opacity: 0.6;
}

.task-card.completed .card-title {
  text-decoration: line-through;
}

.task-card.due-overdue {
  border-left: 3px solid;
}

.task-card.due-today {
  border-left: 3px solid;
}

.task-card.is-dimmed {
  opacity: 0.35;
}

/* ── 完成按钮（右上角，悬停显示） ── */
.complete-btn {
  position: absolute;
  top: -6px;
  right: -6px;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  border: 2px solid var(--c-gray-200);
  background: var(--surface-primary);
  color: var(--c-success);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  opacity: 0;
  transition: opacity 0.15s ease, transform 0.15s ease;
  transform: scale(0.85);
  z-index: 5;
  padding: 0;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.task-card:hover .complete-btn {
  opacity: 1;
  transform: scale(1);
}

.complete-btn:hover {
  background: var(--c-success);
  border-color: var(--c-success);
  color: #fff;
}

/* ── 删除按钮（左上角，悬停显示） ── */
.delete-btn {
  position: absolute;
  top: -6px;
  left: -6px;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  border: 2px solid var(--c-gray-200);
  background: var(--surface-primary);
  color: var(--c-gray-400);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 14px;
  line-height: 1;
  opacity: 0;
  transition: opacity 0.15s ease, transform 0.15s ease;
  transform: scale(0.85);
  z-index: 5;
  padding: 0;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.task-card:hover .delete-btn {
  opacity: 1;
  transform: scale(1);
}

.delete-btn:hover {
  background: var(--c-danger);
  border-color: var(--c-danger);
  color: #fff;
}

/* ── 标题 ── */
.card-title-row {
  display: flex;
  align-items: center;
  gap: 4px;
  min-width: 0;
}

.card-title {
  font-size: 12px;
  font-weight: 600;
  line-height: 1.35;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  color: var(--c-gray-900);
  flex: 1;
  min-width: 0;
}

.recurrence-icon {
  flex-shrink: 0;
  color: var(--c-brand-500);
}

/* ── 底部（标签 + 截止日期） ── */
.card-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 6px;
  margin-top: auto;
}

.card-tags {
  display: flex;
  align-items: center;
  gap: 3px;
  flex: 1;
  min-width: 0;
  overflow: hidden;
}

.tag-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  flex-shrink: 0;
}

.tag-extra {
  font-size: 10px;
  color: var(--c-gray-400);
}

.tag-chip {
  display: inline-flex;
  align-items: center;
  gap: 3px;
  font-size: 10px;
  color: var(--c-gray-500);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 72px;
}

.tag-chip-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  flex-shrink: 0;
}

/* ── 截止日期 ── */
.card-due {
  display: flex;
  align-items: center;
  gap: 4px;
  font-size: 11px;
  color: var(--c-gray-500);
  white-space: nowrap;
  flex-shrink: 0;
}

.due-text {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-weight: 500;
}

.due-status-chip {
  font-size: 9px;
  padding: 1px 5px;
  border-radius: 3px;
  font-weight: 600;
  line-height: 1.4;
}

.checklist-text {
  color: var(--c-gray-400);
  font-variant-numeric: tabular-nums;
}

/* ── 备注 ── */
.card-note {
  margin-top: 4px;
  font-size: 10px;
  line-height: 1.45;
  color: var(--c-gray-500);
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  word-break: break-word;
}

/* ══════════════════════════════════════════ */
/* 密度变体                                   */
/* ══════════════════════════════════════════ */

/* ── 紧凑 ── */
.density-compact {
  padding: 6px 8px;
  min-width: 72px;
  min-height: 44px;
  gap: 0;
}

.density-compact .card-title {
  font-size: 11px;
}

.density-compact .card-footer {
  margin-top: 2px;
  gap: 2px;
}

.density-compact .card-title {
  font-size: 11px;
}

.density-compact .due-status-chip {
  display: none;
}

.density-compact .due-text {
  font-size: 10px;
}

/* ── 详细 ── */
.density-detailed {
  padding: 10px 12px;
  min-width: 140px;
  max-width: 200px;
  gap: 6px;
}

.density-detailed .card-title {
  font-size: 13px;
  white-space: normal;
  word-break: break-word;
}

/* ── 移动端：窄而高，纵向堆叠 ── */
@media (max-width: 767px) {
  .task-card {
    padding: 6px 7px;
    min-height: 50px;
    border-radius: 8px;
    border-left-width: 2px;
    gap: 3px;
    min-width: 60px;
    max-width: 100px;
  }

  /* 标题：允许最多两行换行 */
  .card-title-row {
    align-items: flex-start;
  }

  .card-title {
    font-size: 10px;
    font-weight: 600;
    line-height: 1.25;
    white-space: normal;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
    word-break: break-word;
  }

  .recurrence-icon {
    width: 9px;
    height: 9px;
    margin-top: 1px;
  }

  /* 底部：纵向堆叠 */
  .card-footer {
    flex-direction: column;
    align-items: flex-start;
    gap: 1px;
    margin-top: auto;
  }

  .card-due {
    flex-direction: column;
    align-items: flex-start;
    font-size: 8px;
    gap: 0;
  }

  .due-text {
    font-size: 8px;
    gap: 2px;
  }

  .due-status-chip {
    font-size: 7px;
    padding: 0px 2px;
    border-radius: 2px;
  }

  .checklist-text {
    font-size: 8px;
  }

  /* 标签：极小 chip，最多展示 2 个 */
  .card-tags {
    display: flex !important;
    flex-wrap: wrap;
    gap: 1px;
    margin-bottom: 2px;
  }

  .tag-dot { display: none !important; }
  .tag-extra { display: none !important; }

  .tag-chip {
    display: inline-flex !important;
    font-size: 7px;
    max-width: 44px;
    gap: 2px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .tag-chip-dot {
    width: 4px;
    height: 4px;
  }

  /* 按钮始终可见 */
  .complete-btn,
  .delete-btn {
    opacity: 1;
    transform: scale(1);
  }

  .complete-btn {
    width: 14px;
    height: 14px;
    top: -3px;
    right: -3px;
  }

  .complete-btn svg {
    width: 8px;
    height: 8px;
  }

  .delete-btn {
    display: none;
  }

  /* ---- 移动端密度变体 ---- */

  /* 标准：窄，适中高度 */
  .density-standard {
    max-width: 100px;
    min-width: 68px;
    min-height: 56px;
    padding: 5px 7px;
  }

  /* 紧凑：极窄、极简 */
  .density-compact {
    max-width: 70px;
    min-width: 48px;
    min-height: 38px;
    padding: 3px 5px;
    border-radius: 6px;
    gap: 1px;
  }

  .density-compact .card-title {
    font-size: 9px;
    -webkit-line-clamp: 1;
    white-space: nowrap;
  }

  .density-compact .card-tags {
    display: none !important;
  }

  .density-compact .card-footer {
    display: none;
  }

  /* 详细：最宽、最高 */
  .density-detailed {
    max-width: 130px;
    min-width: 90px;
    min-height: 72px;
    padding: 6px 8px;
    gap: 3px;
  }

  .density-detailed .card-title {
    font-size: 11px;
  }

  .density-detailed .card-note {
    font-size: 8px;
    -webkit-line-clamp: 2;
  }

  .density-detailed .tag-chip {
    font-size: 8px;
    max-width: 52px;
  }
}
</style>
